channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0
  - cadquery=master
  - matplotlib=3.3
  - pip:
      - jupyter-cadquery==3.2.1
      - cadquery-massembly==1.0.0rc0
