channels:
  - pythonocc
  - oce
  - dlr-sc
  - conda-forge
  - cadquery
  - defaults
dependencies:
  - python=3.7
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyterlab=1.2.4
  - notebook=6.0.2
  - pyparsing=2.4.6
  - numpy=1.17.4
  - oce=0.18.3
  - pip=19.3.1
  - pythonocc-core=0.18.2
  - pip:
    - git+https://github.com/CadQuery/cadquery.git
    - sidecar==0.3.0
    - pythreejs==2.1.1
    - jupyter_cadquery==0.9.3
